### ISSUE TITLE
Create JS versions of core component backing models

### ISSUE THREAD

**Issue by CodeByAlex** [storybookjs/aem#97] opened 2020-05-18 11:01 UTC
This is high priority and required for core component usage in the storybook

- [x] `core/wcm/components/tabs/v1/tabs`
- [ ] `core/wcm/components/page/v1/page`
- [ ] `core/wcm/components/form/options/v2/options`
- [ ] `core/wcm/components/form/hidden/v2/hidden`
- [ ] `core/wcm/components/form/container/v2/container`
- [x] `core/wcm/components/form/button/v2/button`
- [x] `core/wcm/components/form/text/v2/text`
- [ ] `core/wcm/components/sharing/v1/sharing`
- [ ] `core/wcm/components/contentfragment/v1/contentfragment`
- [ ] `core/wcm/components/embed/v1/embed/embeddable/youtube`
- [ ] `core/wcm/components/embed/v1/embed/embeddable`
- [ ] `core/wcm/components/embed/v1/embed`
- [x] `core/wcm/components/title/v2/title`
- [x] `core/wcm/components/accordion/v1/accordion`
- [ ] `core/wcm/components/separator/v1/separator`
- [ ] `core/wcm/components/navigation/v1/navigation`
- [ ] `core/wcm/components/carousel/v1/carousel`
- [x] `core/wcm/components/image/v2/image`
- [ ] `core/wcm/components/search/v1/search`
- [ ] `core/wcm/components/container/v1/container`
- [ ] `core/wcm/components/contentfragmentlist/v1/contentfragmentlist`
- [x] `core/wcm/components/button/v1/button`
- [ ] `core/wcm/components/download/v1/download`
- [x] `core/wcm/components/teaser/v1/teaser`
- [x] `core/wcm/components/list/v1/list`
- [ ] `core/wcm/components/languagenavigation/v1/languagenavigation`
- [x] `core/wcm/components/text/v2/text`
- [x] `core/wcm/components/breadcrumb/v2/breadcrumb`
- [ ] `core/wcm/components/experiencefragment/v1/experiencefragment`

**Comment by jpica11** [comment] 2020-05-19 23:13
I can pick up a few of these, thinking I'll start with button if no one has done that yet?

**Comment by CodeByAlex** [comment] 2020-05-19 23:15
That would be awesome! Any models you don’t see in here are available to work on: https://github.com/storybookjs/aem/tree/master/examples/aem-core-components/models

**Comment by tripodsan** [comment] 2020-05-20 03:49
@jpica11 you can start by copying the models from here:
https://github.com/adobe/aem-core-wcm-components/blob/master/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/BreadcrumbImpl.java

btw: I hope we can move the stories and js models to the `aem-core-wcm-components` repository eventually. and then create a npm release of the storified version.

**Comment by tripodsan** [comment] 2020-05-20 04:07
I think this issue is a duplicate of #7

**Closed** 2020-11-01 14:58 UTC
Labels: good first issue, help wanted
